# This is a config for E2B sandbox template.
# You can use template ID (p0s9ts2df8gc30dcoza6) or template name (nova-nextjs-ashek-test) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox("nova-nextjs-ashek-test") # Sync sandbox
# sandbox = await AsyncSandbox.create("nova-nextjs-ashek-test") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('nova-nextjs-ashek-test')

team_id = "1cda1176-2588-4a79-90d5-14fa1588fada"
start_cmd = "/compile_page.sh"
dockerfile = "e2b.Dockerfile"
template_name = "nova-nextjs-ashek-test"
template_id = "p0s9ts2df8gc30dcoza6"
